/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 0b7449d9eff920358a2a0ff714558d7c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		DB: D1Database;
		LOADER: WorkerLoader;
		AI: Ai;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
	}
}
interface Env extends Cloudflare.Env {}
